# 语言文件 [可选 中文简体:zh_CN]
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 是否不显示 省和市后缀 开启后例如 江苏省 会显示为 江苏
removeProvinceAndCity: false

unknown: "未知"

local: "内网IP"

# 数据来源 自己选择一个最准确的即可
# offline 本地数据源模式(只支持ipv4 百分之99.9数据准确性)
# ipPlus360 在线api模式(支持ipv4/ipv6 付费 必需先购买key填下面)
# ipApi 在线api模式(支持ipv4/ipv6 免费 限制 每分钟请求 45 次,也就是一分钟服务器同时进45人 官网:https://ip-api.com)
# whois 在线api模式(支持ipv4/ipv6 免费 太平洋网络IP地址 官网:https://whois.pconline.com.cn)
# voreApi 在线api模式(支持ipv4/ipv6 免费 vore-Api 官网:https://api.vore.top)
dataSource: offline

# ipPlus360模式 ipv4在线归属地(有试用额度) 购买地址: https://mall.ipplus360.com/pros/IPVFourGeoAPI
ipPlus360Ipv4Key: 123456
# ipPlus360模式 ipv6在线归属地 购买地址: https://mall.ipplus360.com/pros/IPGeoAPI
ipPlus360Ipv6Key: 123456
